#!/usr/bin/env python3
"""Collect MTE-relevant information from a connected iOS device.

Runs on the host, needs no jailbreak: reads device identity over lockdown,
optionally pulls crash reports and catches a syslog window, writes a
redacted report bundle you can commit as-is.

Usage:
    python3 scripts/mte_device_report.py                     # identity report
    python3 scripts/mte_device_report.py --crashes           # + crash reports
    python3 scripts/mte_device_report.py --syslog 30         # + 30s syslog
    python3 scripts/mte_device_report.py -udid <UDID> --out contributions

Requires libimobiledevice (idevice_id, ideviceinfo, idevicecrashreport,
idevicesyslog). Device must be unlocked and trusted.

Exit codes: 0 = report written; 2 = no device / missing tool.
"""

import argparse
import os
import plistlib
import shutil
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import contrib_common as cc  # noqa: E402
import mte_crash_scan  # noqa: E402

# What the KB wants from each device class.
WANTED = {
    True: [
        "crash reports from this device (any app), especially anything with "
        "EXC_ARM_MTE_TAGCHECK_FAIL / MTE_FAIL 262",
        "a syslog window while a tagged app starts up",
        "which third-party apps crash here but not on an older iPhone",
        "the kernelcache build id (scripts/fetch_kernelcache.py needs no device)",
        "the MTE instruction census of its kernelcache (mte_insn_census.py)",
        "hw feature bits: on-device code reading ID_AA64PFR1_EL1 / "
        "ID_AA64ISAR3_EL1 (CPA), or a kernelcache symbol dump",
    ],
    False: [
        "control data: crash reports that are clean here but tagged on A19 "
        "(same app, same version), to separate real bugs from tagging-only ones",
        "kernelcache census numbers for the pre-MTE baseline",
        "panic logs from normal use, for the refcount/overflow side of Tier 9",
    ],
    None: [
        "run this script and paste the identity block: an unknown product "
        "type is itself a useful data point",
    ],
}


def run(cmd, timeout=60):
    try:
        return subprocess.run(cmd, capture_output=True, text=True,
                              timeout=timeout)
    except FileNotFoundError:
        return None
    except subprocess.TimeoutExpired:
        return None


def list_devices():
    """Return (devices, reason). devices is a list (possibly empty) when the
    tools worked, else None with a reason string."""
    if not shutil.which("idevice_id"):
        return None, "idevice_id not found: install libimobiledevice-utils"
    result = run(["idevice_id", "-l"], timeout=20)
    if result is None:
        return None, "idevice_id did not respond (timed out)"
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip().splitlines()
        detail = detail[0] if detail else "exit %d" % result.returncode
        return None, detail
    return [line.strip() for line in result.stdout.splitlines() if line.strip()], None


def device_info(udid):
    if not shutil.which("ideviceinfo"):
        return None
    cmd = ["ideviceinfo", "-x"]
    if udid:
        cmd += ["-u", udid]
    result = run(cmd, timeout=60)
    if result is None or result.returncode != 0:
        return None
    try:
        return plistlib.loads(result.stdout.encode("utf-8", "replace"))
    except Exception:
        return None


KEYS_WORTH_KEEPING = [
    "ProductType", "HardwareModel", "HardwarePlatform", "ProductVersion",
    "BuildVersion", "CPUArchitecture", "DeviceClass", "ModelNumber",
    "RegionInfo", "ProductName", "BoardId", "BuildID",
]


def build_report(info, product_type, family, chip, capable, note):
    lines = ["# Device report: %s" % (product_type or "unknown"), ""]
    lines.append("Generated by `scripts/mte_device_report.py` on %s."
                 % time.strftime("%Y-%m-%d %H:%M:%S"))
    lines.append("")
    lines.append("## Identity")
    lines.append("")
    for key in KEYS_WORTH_KEEPING:
        if key in info:
            lines.append("- %s: %s" % (key, info[key]))
    lines.append("")
    lines.append("## MTE verdict")
    lines.append("")
    lines.append("- family: %s" % family)
    lines.append("- chip: %s" % chip)
    if capable is True:
        lines.append("- MTE/MIE capable: yes%s" % (" (%s)" % note if note else ""))
    elif capable is False:
        lines.append("- MTE/MIE capable: no (pre-MIE silicon, useful as a control)")
    else:
        lines.append("- MTE/MIE capable: unknown (%s)" % note)
    lines.append("")
    lines.append("## What this device can contribute")
    lines.append("")
    for item in WANTED[capable]:
        lines.append("- %s" % item)
    lines.append("")
    return "\n".join(lines), capable


def capture_syslog(udid, seconds, path):
    if not shutil.which("idevicesyslog"):
        print("idevicesyslog not found, skipping syslog capture", file=sys.stderr)
        return None
    cmd = ["idevicesyslog", "--no-colors", "-o", path]
    if udid:
        cmd += ["-u", udid]
    print("capturing syslog for %ds -> %s" % (seconds, path))
    proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL,
                            stderr=subprocess.DEVNULL)
    try:
        proc.wait(timeout=seconds)
    except subprocess.TimeoutExpired:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        text = handle.read()
    findings = cc.scan_blob(text)
    return {"path": path, "lines": text.count("\n"), "findings": findings}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-u", "--udid", default=None)
    parser.add_argument("--plist", metavar="FILE",
                        help="offline mode: use a saved `ideviceinfo -x` plist "
                             "instead of probing a device (implies --no device)")
    parser.add_argument("--out", default="contributions")
    parser.add_argument("--crashes", action="store_true",
                        help="pull crash reports and scan them for MTE markers")
    parser.add_argument("--keep", action="store_true",
                        help="do not remove pulled crash reports from the device")
    parser.add_argument("--syslog", type=int, metavar="SECONDS", default=0,
                        help="capture this many seconds of syslog")
    parser.add_argument("--no-anonymize", action="store_true")
    args = parser.parse_args(argv)

    if args.plist:
        try:
            with open(args.plist, "rb") as handle:
                info = plistlib.load(handle)
        except Exception as exc:
            print("cannot read plist %s: %s" % (args.plist, exc), file=sys.stderr)
            return 2
        udid = None
        if args.crashes or args.syslog:
            print("offline mode: --crashes/--syslog need a connected device",
                  file=sys.stderr)
            return 2
    else:
        devices, reason = list_devices()
        if devices is None:
            print("cannot list devices: %s" % reason, file=sys.stderr)
            print("hints: usbmuxd running (sudo systemctl start usbmuxd), cable in a "
                  "data port, device unlocked and trusted, then re-run.",
                  file=sys.stderr)
            return 2
        if not devices:
            print("no device found over USB.", file=sys.stderr)
            print("checklist: cable in a data port, device unlocked, tap Trust, "
                  "usbmuxd running (sudo systemctl start usbmuxd), then re-run.",
                  file=sys.stderr)
            return 2
        udid = args.udid or devices[0]
        if args.udid and args.udid not in devices:
            print("warning: %s does not match a connected device, trying anyway"
                  % args.udid, file=sys.stderr)
        info = device_info(udid)
        if info is None:
            print("could not read device info (locked? not trusted?)", file=sys.stderr)
            return 2

    product_type = str(info.get("ProductType", ""))
    family, chip, capable, note = cc.device_verdict(product_type)
    # unique identifiers never reach the report, even before text redaction
    safe_info, identifiers_redacted = cc.redact_obj(dict(info))
    report, _ = build_report(safe_info, product_type, family, chip, capable, note)

    stamp = time.strftime("%Y%m%d-%H%M%S")
    bundle = os.path.join(args.out, "%s-%s" % (stamp, product_type or "unknown"))

    if args.crashes:
        rc = mte_crash_scan.pull_from_device(udid, keep=args.keep)
        if rc == 0:
            reports = mte_crash_scan.find_reports([mte_crash_scan.PULL_DIR])
            hits = []
            for path in reports:
                try:
                    summary = cc.analyse(path)
                except Exception as exc:
                    print("parse failed for %s: %s" % (path, exc), file=sys.stderr)
                    continue
                if summary["is_mte"]:
                    hits.append(summary)
            report += "\n## Crash reports\n\n"
            report += "- pulled: %d\n- with MTE markers: %d\n" % (len(reports), len(hits))
            for summary in hits:
                report += "\n" + cc.corpus_entry(summary) + "\n"

    if args.syslog:
        log_path = os.path.join(bundle, "syslog.txt")
        result = capture_syslog(udid, args.syslog, log_path)
        if result:
            report += "\n## Syslog capture\n\n"
            report += ("- %d lines in %ds\n" % (result["lines"], args.syslog))
            if result["findings"]:
                report += "- MTE markers: %s\n" % ", ".join(
                    "%s x%d" % (k, v[0]) for k, v in sorted(result["findings"].items()))
            else:
                report += "- MTE markers: none\n"

    redactions = {}
    if not args.no_anonymize:
        report = cc.redact(report, redactions)

    next_steps = [
        "",
        "## Submitting this report",
        "",
        "```",
        "git checkout -b contrib/%s-%s" % (product_type or "device", stamp[:8]),
        "git add %s" % os.path.join(bundle, "device-report.md"),
        "git commit -m 'contrib: device report %s'" % (product_type or "unknown"),
        "gh pr create --fill --title 'contrib: %s device report'"
        % (product_type or "unknown"),
        "```",
        "",
        "Raw crash reports stay local (`.ips` is gitignored); paste anything "
        "notable into the report by hand.",
        "",
    ]
    report += "\n".join(next_steps)

    report_path = os.path.join(bundle, "device-report.md")
    cc.write_atomic(report_path, report)

    print(report)
    print("-" * 60)
    print("wrote %s" % report_path)
    if identifiers_redacted:
        print("blanked %d identifier field(s) before rendering" % identifiers_redacted)
    if redactions:
        print("redacted: %s" % ", ".join("%s x%d" % (k, v)
                                         for k, v in sorted(redactions.items())))
    print()
    print("to contribute:")
    print("  git checkout -b contrib/%s-%s" % (product_type or "device", stamp[:8]))
    print("  git add %s" % report_path)
    print("  git commit -m 'contrib: device report %s'" % (product_type or "unknown"))
    print("  gh pr create --fill --title 'contrib: %s device report'"
          % (product_type or "unknown"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
